version: "3"
services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: expense-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expense_db
      MYSQL_USER: expense_user
      MYSQL_PASSWORD: expense_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: expense-backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: expense_user
      DB_PASSWORD: expense_password
      DB_NAME: expense_db
    ports:
      - "8080:8080"
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: expense_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
volumes:
  mysql-data:
